name: "AWS Deploy"

on:
  push:
    branches:
      - main            # could be 'master' on older repos
   workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug
env:
  AWS_REGION: eu-south-1
  IAM_ROLE: arn:aws:iam::516175876821:role/GitHubActionIACRole
  AW_BUCKET: preview-2764
  AWS_CLOUDFRONT_ID: E3RURJRAPWO5IP

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Build
        run: |
          npm ci
          npm run build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Deploy
        uses: jonelantha/gatsby-s3-action@v1
        with:
          dest-s3-bucket: ${{ env.AWS_REGION }}
          cloudfront-id-to-invalidate: ${{ env.AWS_CLOUDFRONT_ID }}