name: "Deploy AWS"

on:
  push:
    branches:
      - main
    paths:
      - 'src/app/**'
      - '.github/workflows/*.yml'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug
      environment:
        description: 'Which environment to update.'
        type: choice
        default: 'dev'
        required: true 
        options:
        - dev
        - prod
  # Allows external webhook trigger
  repository_dispatch:
    types:
      - webhook

env:
 AWS_REGION: eu-central-1
 ENVIRONMENT:  github.event.inputs.environment || 'dev'
 AWS_BUCKET: ${{ github.event.inputs.environment == 'dev' && 'pn-d-website-4229' || 'cms-p-website-2428' }}
 AWS_CLOUDFRONT_ID: ${{ github.event.inputs.environment == 'dev' && 'E3N4Q7VLCPYZUD' || 'E3N3EGPA4RVVH1' }} 
 STRAPI_URL: ${{ github.event.inputs.environment == 'dev' && 'https://cms.poc.pn.pagopa.it' || 'http://cms-alb-1558790704.eu-central-1.elb.amazonaws.com' }} 
 
defaults:
  run:
    shell: bash
    working-directory: src/app

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  deploy:
    name: "deploy"
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }} 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Build
        env: 
          STRAPI_TOKEN: ${{ secrets.STRAPI_TOKEN }}
          STRAPI_API_URL: ${{ env.STRAPI_URL }}
        run: |
          yarn install
          yarn build
      - name: Check 
        run: | 
          pwd
          ls -lrt
      - name: s3-publish
        uses: jonelantha/gatsby-s3-action@v1
        with:
          dest-s3-bucket: ${{ env.AWS_BUCKET }}
          cloudfront-id-to-invalidate: ${{ env.AWS_CLOUDFRONT_ID }}
          public-source-path: src/app/public